MVCLibaryApp/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLibaryApp.Models.Entity;

namespace MVCLibaryApp.Controllers
{
    public class DeliveryController : Controller
    {
        // GET: Delivery
        DBKITABXANAEntities db = new DBKITABXANAEntities();
        public ActionResult Index()
        {
            var action = db.TBLACTION.Where(m=>m.SD == false).ToList();
            return View(action);
        }
        public ActionResult History()
        {
            var action = db.TBLACTION.Where(m => m.SD == true).ToList();
            return View(action);
        }
        [HttpGet]
        public ActionResult DeliveryAdd()
        {
            List<SelectListItem> book = (from x in db.TBLBOOK.Where(z=>z.BOOKSTATUS == true && z.SD == true).ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.NAME,
                                             Value = x.ID.ToString()
                                         }).ToList();
            ViewBag.book = book;

            List<SelectListItem> member = (from m in db.TBLMEMBERS.Where(z=>z.SD == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = m.NAME + " " + m.SURNAME + "{"+ m.MAIL + "}",
                                               Value = m.ID.ToString()
                                           }).ToList();
            ViewBag.member = member;

            List<SelectListItem> personal = (from p in db.TBLPERSONAL.Where(z => z.SD == true).ToList()
                                             select new SelectListItem
                                             {
                                                 Text = p.PERSONAL,
                                                 Value = p.ID.ToString()
                                             }).ToList();
            ViewBag.personal = personal;

            return View();
        }
        [HttpPost]
        public ActionResult DeliveryAdd(TBLACTION a)
        {
            var bk = db.TBLBOOK.Where(x => x.ID == a.TBLBOOK.ID).FirstOrDefault();
            var mb = db.TBLMEMBERS.Where(x => x.ID == a.TBLMEMBERS.ID).FirstOrDefault();
            var ps = db.TBLPERSONAL.Where(x => x.ID == a.TBLPERSONAL.ID).FirstOrDefault();

            
            if ( bk.BOOKSTATUS == false)
            {
                bk.BOOKSTATUS = false;
                return RedirectPermanent("/Book/Index/");

            }
            a.TBLBOOK = bk;
            a.TBLMEMBERS = mb;
            a.TBLPERSONAL = ps;
            a.SD = false;           
            db.TBLACTION.Add(a);
            db.SaveChanges();
            return RedirectToAction("Index"); 
            //var book = db.TBLBOOK.Where(m => m.ID == a.BOOK).FirstOrDefault();
            //var member = db.TBLMEMBERS.Where(m => m.ID == a.MEMBER).FirstOrDefault();
            //var bId = db.TBLBOOK.Find(book.ID);
            //int stock = Convert.ToInt32(bId.STOCK);
            //int resultStck = stock = stock - 1;
            //if (stock == 0 || stock < 0 || bId.BOOKSTATUS == false)
            //{
            //    bId.BOOKSTATUS = false;
            //    return RedirectPermanent("/Book/ChangeBook/" + bId.ID);

            //}
            //var reBook = db.TBLACTION.Where(m => m.MEMBER == member.ID && m.BOOK == book.ID).FirstOrDefault();
            //if (reBook.ID == book.ID && reBook.ID == member.ID) 
            //{
            //    Response.Write("................................................Such information is already available");
            //    return View();
            //}
            //if (stock == 0)
            //{
            //    bId.BOOKSTATUS = false;
            //}
            //bId.STOCK = Convert.ToInt32(resultStck);
        }
        public ActionResult Return(TBLACTION a)
        {
            var retBook = db.TBLACTION.Find(a.ID);
            DateTime d1 = DateTime.Parse(retBook.RETURNDATE.ToString());
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;
            ViewBag.fine = d3.TotalDays;
            return View("Return", retBook);
        }
        public ActionResult UpdateRetToDelivery(TBLACTION a)
        {
            var retBook = db.TBLACTION.Find(a.ID);
            retBook.RETURNNOW = a.RETURNNOW;          
            retBook.SD = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCLibaryApp/Views/Delivery/DeliveryAdd.cshtml
@model  MVCLibaryApp.Models.Entity.TBLACTION
@{
    ViewBag.Title = "DeliveryAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DeliveryAdd", "Delivery", FormMethod.Post))
{
    <label>Book</label>
    @Html.DropDownListFor(x=>x.TBLBOOK.ID, (List<SelectListItem>)ViewBag.book, new { @class = "form-control" })
    <br />
    <label>Member</label>
    @Html.DropDownListFor(m => m.TBLMEMBERS.ID, (List<SelectListItem>)ViewBag.member, new { @class = "form-control" })
    <br />
    <label>Personal</label>
    @Html.DropDownListFor(m => m.TBLPERSONAL.ID, (List<SelectListItem>)ViewBag.personal, new { @class = "form-control" })
    <br />
    <label>Delivery date</label>
    <input type="text" name="DELIVERYDATE" class = "form-control" value="@DateTime.Now.ToShortDateString()" />
    <br />
    <label>Return date</label>
    <input type="text" name="RETURNDATE" class = "form-control" value="@DateTime.Now.AddDays(7).ToShortDateString()" />
    <br />
    <button class="btn btn-primary" style="background-color:#07f7a6; color:#ffffff">Delivery now</button>
}

MVCLibaryApp/Views/Delivery/History.cshtml
@using MVCLibaryApp.Models.Entity
@model List<TBLACTION>
@{
    ViewBag.Title = "History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>History</h2>
<br />
<a href="/Fines/index" class="btn btn-warning">The fines members</a>
<br />
<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>

            <th>#</th>
            <th>Member</th>
            <th>Book</th>
            <th>Personal</th>
            <th>Delivery date</th>
            <th>Returned date</th>
        </tr>
    </thead>

    @foreach (var x in Model)
    {
        <tr style="color:#0e085a; font-size:20px">
            <td>@x.ID</td>
            <td>@x.TBLMEMBERS.NAME &nbsp; @x.TBLMEMBERS.SURNAME</td>
            <td>@x.TBLBOOK.NAME</td>
            <td>@x.TBLPERSONAL.PERSONAL</td>
            <td>@Convert.ToDateTime(x.DELIVERYDATE).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(x.RETURNNOW).ToString("dd/MM/yyyy")</td>
            <td>
                <a href="/Delivery/Detail/@x.ID" class="btn btn-primary" style="background-color:#4f2dc4; color:#ffffff">Detail</a>
            </td>
        </tr>
    }
</table>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

MVCLibaryApp/Views/Delivery/Index.cshtml
@using MVCLibaryApp.Models.Entity
@model List<TBLACTION>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Return book</h2>
<table class="table table-bordered" >
    <tr>
        <th>#</th>
        <th>Member</th>
        <th>Book</th>
        <th>Personal</th>
        <th>Delivery date</th>
        <th>Return date</th>
        <th>Return book</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.TBLMEMBERS.NAME &nbsp; @x.TBLMEMBERS.SURNAME</td>
            <td>@x.TBLBOOK.NAME</td>
            <td>@x.TBLPERSONAL.PERSONAL</td>
            <td>@Convert.ToDateTime(x.DELIVERYDATE).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(x.RETURNDATE).ToString("dd/MM/yyyy")</td>
            <td>
                <a href="/Delivery/Return/@x.ID" class="btn btn-primary"style="background-color:#4f2dc4; color:#ffffff">Return book</a>
            </td>

        </tr>
    }
</table>

MVCLibaryApp/Views/Delivery/Return.cshtml
@model MVCLibaryApp.Models.Entity.TBLACTION
@{
    ViewBag.Title = "Return";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Return book</h2>

@using (Html.BeginForm("UpdateRetToDelivery", "Delivery", FormMethod.Post))
{
    @Html.HiddenFor(m => m.ID, new { @class = "form-control" })

    <label>Book</label>
    @Html.TextBoxFor(m => m.TBLBOOK.NAME, new { @class = "form-control" })
    <br />

    <label>Member</label>
    @Html.TextBoxFor(m => m.TBLMEMBERS.NAME, new { @class = "form-control" })
    <br />

    <label> Personal </label>
    @Html.TextBoxFor(m => m.TBLPERSONAL.PERSONAL, new { @class = "form-control" })
    <br />

    <label>Delivery date</label>
    @Html.TextBoxFor(m => m.DELIVERYDATE, "{0: dd.MM.yyyy}", new { @class = "form-control" })
    <br />

    <label>End date</label>
    @Html.TextBoxFor(m => m.RETURNDATE, "{0: dd.MM.yyyy}", new { @class = "form-control" })
    <br />

    <label>Return date now</label>
    <input type="text" name="RETURNNOW" class="form-control" value="@DateTime.Now.ToShortDateString()" />
    <br />

    <label>Total fine to date</label>
    <input type="text" name="fine" class="form-control" id="fine" value="@ViewBag.fine" />
    <br />
    <button class="btn btn-primary" style="background-color:#07f7a6; color:#ffffff">Return now</button>
}